In [31]:
import pandas
from pandas import DataFrame
import jaydebeapi

<h3>pip install pyArango</h3>

In [32]:
from pyArango.connection import*
from pyArango.query import*
import pyArango.validation as VAL

<h3>設計一個 SQL 資料庫表格，欲將此 CSV 匯入</h3>

In [33]:
data=pandas.read_csv("C:\\Users\\user\\anaconda3\\Projects\\data\\movies_data.csv",encoding='utf-8')
data

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
0,#Gadhvi (He thought he was Gandhi),2019,109,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
1,#Yaaram,2019,110,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
2,...Aur Pyaar Ho Gaya,1997,147,"Comedy, Drama, Musical",4.7,827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor
3,...Yahaan,2005,142,"Drama, Romance, War",7.4,1086,Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma
4,?: A Question Mark,2012,82,"Horror, Mystery, Thriller",5.6,326,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia
...,...,...,...,...,...,...,...,...,...,...
5654,Zubaan,2015,115,Drama,6.1,408,Mozez Singh,Vicky Kaushal,Sarah Jane Dias,Raaghavv Chanana
5655,Zubeidaa,2001,153,"Biography, Drama, History",6.2,1496,Shyam Benegal,Karisma Kapoor,Rekha,Manoj Bajpayee
5656,Zulm Ki Zanjeer,1989,125,"Action, Crime, Drama",5.8,44,S.P. Muthuraman,Chiranjeevi,Jayamalini,Rajinikanth
5657,Zulmi,1999,129,"Action, Drama",4.5,655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani
5658,Zulm-O-Sitam,1998,130,"Action, Drama",6.2,20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja

<h3>ArangoDB 資料庫</h3>

In [4]:
db_ip='localhost'

db_conn=Connection(
    arangoURL='http://%s:8529'%db_ip,
    username='emprogria',
    password='emprogria'
)

In [5]:
db=db_conn['Emprogria']
db_collection=db.collections['StockInfo2']

<h3>資料筆數</h3>

In [6]:
aql='FOR doc IN StockInfo2 RETURN doc'
sub_collections=db.AQLQuery(aql, rawResults=False, batchSize=30000) #false結構化,資料子集合
print('筆數: %d' % len(sub_collections.response['result']))

筆數: 1597

<h3>此 SQL 資料庫表格需要衍生一個索引欄位，規則為：MOV0001，後四碼為序號</h3>

In [36]:
for i in range(data.shape[0]):
    data['ID'][i]="MOV"+'%04d'%int(i+1)
data

C:\Users\user\AppData\Local\Temp/ipykernel_15120/2087603487.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['ID'][i]="MOV"+'%04d'%int(i+1)

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3,ID
0,#Gadhvi (He thought he was Gandhi),2019,109,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid,MOV0001
1,#Yaaram,2019,110,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor,MOV0002
2,...Aur Pyaar Ho Gaya,1997,147,"Comedy, Drama, Musical",4.7,827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor,MOV0003
3,...Yahaan,2005,142,"Drama, Romance, War",7.4,1086,Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma,MOV0004
4,?: A Question Mark,2012,82,"Horror, Mystery, Thriller",5.6,326,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia,MOV0005
...,...,...,...,...,...,...,...,...,...,...,...
5654,Zubaan,2015,115,Drama,6.1,408,Mozez Singh,Vicky Kaushal,Sarah Jane Dias,Raaghavv Chanana,MOV5655
5655,Zubeidaa,2001,153,"Biography, Drama, History",6.2,1496,Shyam Benegal,Karisma Kapoor,Rekha,Manoj Bajpayee,MOV5656
5656,Zulm Ki Zanjeer,1989,125,"Action, Crime, Drama",5.8,44,S.P. Muthuraman,Chiranjeevi,Jayamalini,Rajinikanth,MOV5657
5657,Zulmi,1999,129,"Action, Drama",4.5,655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani,MOV5658
5658,Zulm-O-Sitam,1998,130,"Action, Drama",6.2,20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja,MOV5659

In [ ]:
aql='FOR doc IN StockInfo2 update {_key: doc._key,"index" : "MOV"left(doc.timestamp,8)} into StockInfo2 RETURN doc'
sub_collections=db.AQLQuery(aql, rawResults=False, batchSize=30000) #false結構化,資料子集合
queryResult=sub_collections.response['result']
_resultSet=[]
for doc in queryResult:
    _resultSet.append(doc)
DataFrame(data=_resultSet)

<h3>將此資料集依照樣本時間 (timestamp) 由大到小排序</h3>

In [8]:
aql='FOR doc IN StockInfo2 sort doc.`timestamp` desc RETURN doc'
sub_collections=db.AQLQuery(aql, rawResults=False, batchSize=30000) #false結構化,資料子集合
queryResult=sub_collections.response['result']
_resultSet=[]
for doc in queryResult:
    _resultSet.append(doc)
DataFrame(data=_resultSet)

,_key,_id,_rev,title,score,id,comms_num,created,body,timestamp,YM,url
0,59408,StockInfo2/59408,_dZHSkeS--F,Comment,1,hj2gp8j,0,1635890498,">even english\n\n""even English"" Bad grammar an...",2021-11-03 00:01:38,2021-11-,NaN
1,58961,StockInfo2/58961,_dZHSkde--W,Do the covid vaccines actually prevent covid?,2,qky46m,0,1635834443,NaN,2021-11-02 08:27:23,2021-11-,https://youtu.be/nSHlBpEgAAI
2,59409,StockInfo2/59409,_dZHSkeS--G,Comment,1,hiywnx9,0,1635822932,Smart girl. Stand up for your right to chose....,2021-11-02 05:15:32,2021-11-,NaN
3,59410,StockInfo2/59410,_dZHSkeS--H,Comment,1,hiywdmg,0,1635822786,It’s over!,2021-11-02 05:13:06,2021-11-,NaN
4,59411,StockInfo2/59411,_dZHSkeS--I,Comment,1,hiywaa5,0,1635822738,Horrible.,2021-11-02 05:12:18,2021-11-,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1592,59403,StockInfo2/59403,_dZHSkeS--A,I am a father of five unvaccinated children. A...,1,1v3c8o,1,1389596148,NaN,2014-01-13 08:55:48,2014-01-,http://www.np.reddit.com/r/conspiracy/comments...
1593,59404,StockInfo2/59404,_dZHSkeS--B,Love Them. Protect Them. Never Inject Them.,1,1v3c3i,2,1389595987,NaN,2014-01-13 08:53:07,2014-01-,http://i.imgur.com/SkB0a6T.jpg
1594,59405,StockInfo2/59405,_dZHSkeS--C,Vaccines Are Just Asping For Trouble,2,1v3brt,1,1389595651,NaN,2014-01-13 08:47:31,2014-01-,http://i.imgur.com/bIPQpbv.jpg
1595,59406,StockInfo2/59406,_dZHSkeS--D,Dr. Harper explained in her presentation that ...,1,1v3blj,1,1389595497,NaN,2014-01-13 08:44:57,2014-01-,http://www.feelguide.com/2013/07/16/lead-devel...
1596,59407,StockInfo2/59407,_dZHSkeS--E,Polio arose in the US at a period where pestic...,1,1v3bh2,1,1389595375,NaN,2014-01-13 08:42:55,2014-01-,http://www.np.reddit.com/r/medicine/comments/1...

<h3>開啟H2資料庫</h3>

In [9]:
dbConnection = jaydebeapi.connect(
    "org.h2.Driver",
    "jdbc:h2:C:/Users/user/anaconda3/Projects/data/H2",
    ["SA", ""],
    "C:/Java/h2/bin/h2-1.4.200.jar")

dbCursor = dbConnection.cursor()

<h3>設計 SQL 語句統計各 SCORE 小計筆數</h3>

In [10]:
_sql=[
    "SELECT score,count(score),",
    "FROM STOCKINFO2",
]

dbCursor.execute(' '.join(_sql))
resultSet = dbCursor.fetchall()
resultSet

[('7', 1)]

<h3>關閉H2資料庫</h3>

In [11]:
dbCursor.close()
dbConnection.close()

<h3>設計 AQL 語句統計各 SCORE 小計筆數</h3>