In [1]:
import numpy
import pandas

In [2]:
packages = []
num_of_pack = 8

for i in range(num_of_pack):
    packages.append(dict(id='PCK-%d' % (i + 1), 
                         volume=numpy.random.randint(1, 5) * 500, 
                         weight=numpy.random.randint(1, 5) * 300, 
                         piece=numpy.random.randint(1, 5) * 100))
    
package_dataset = pandas.DataFrame(data=packages)
package_dataset

      id  volume  weight  piece
0  PCK-1    1500    1200    400
1  PCK-2    1500    1200    300
2  PCK-3    1500     600    300
3  PCK-4     500     900    400
4  PCK-5    1500     300    400
5  PCK-6    1000     900    100
6  PCK-7     500     900    200
7  PCK-8     500    1200    200

In [3]:
storages = []
num_of_bin = 64

for i in range(num_of_bin):
    storages.append(dict(id='STG-%02d' % (i + 1), 
                         max_volume=numpy.random.randint(50, 100) * 500, 
                         max_weight=numpy.random.randint(10, 80) * 300,
                         occupied_volume=0, occupied_weight=0,
                         packages=[])                         
                   )
    
storage_dataset = pandas.DataFrame(data=storages)
storage_dataset.head()

       id  max_volume  max_weight  occupied_volume  occupied_weight packages
0  STG-01       37500       22500                0                0       []
1  STG-02       26500        3000                0                0       []
2  STG-03       27000        5100                0                0       []
3  STG-04       29000       11400                0                0       []
4  STG-05       27000       10800                0                0       []

In [4]:
num_of_shipment = 100

for i in range(num_of_shipment):
    package = package_dataset.sample(1)
    
    for j in range(storage_dataset.shape[0]):
        storage = storage_dataset.iloc[j]

        occupied_weight = storage['occupied_weight'] + package['weight']
        max_weight = storage['max_weight']
        
        if max_weight.item() >= occupied_weight.item():
            occupied_volume = storage['occupied_volume'] + package['volume']
            max_volume = storage['max_volume']
            
            if occupied_volume.item() <= max_volume.item():
                storage['packages'].append(package['id'].values[0])

storage_dataset.head()

,id,max_volume,max_weight,occupied_volume,occupied_weight,packages
0,STG-01,49500,22500,0,0,"[PCK-1, PCK-4, PCK-5, PCK-2, PCK-7, PCK-6, PCK..."
1,STG-02,38500,7200,0,0,"[PCK-1, PCK-4, PCK-5, PCK-2, PCK-7, PCK-6, PCK..."
2,STG-03,30000,11100,0,0,"[PCK-1, PCK-4, PCK-5, PCK-2, PCK-7, PCK-6, PCK..."
3,STG-04,39000,15600,0,0,"[PCK-1, PCK-4, PCK-5, PCK-2, PCK-7, PCK-6, PCK..."
4,STG-05,36000,14100,0,0,"[PCK-1, PCK-4, PCK-5, PCK-2, PCK-7, PCK-6, PCK..."